---
title: "Information technology"
output:
  html_document:
    toc: true               # Table of content true
    toc_depth: 4            # Up to three depths of headings (specified by #, ## and html_document
    toc_float: true
    number_sections: false  # If you want number sections at each table header
  #   theme: united           # Many options for theme, this one is my favorite.
  #   highlight: tango        # Specifies the syntax highlighting style
  #   css: styles_demography.css
  # revealjs::revealjs_presentation:
  #   dev: 'svg'
  #   self_contained: false
  #   reveal_plugins: ["notes", "search"]
  #   reveal_options:
  #     slideNumber: true
  #     previewLinks: true
  # word_document:
  #   always_allow_html: yes
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(echo          = FALSE, 
                      warning       = FALSE, 
                      message       = FALSE, 
                      warning       = FALSE, 
                      fig.fullwidth = TRUE, 
                      paged.print   = FALSE, 
                      comment       = NA)

```



\
\
\


## **`r 'Q146'`**
```{r K1, fig.width = 22, fig.height = 8}

if (is.null(ord5_plots_sub[['K1_graph']]) == FALSE) {
  
  ord5_plots_sub[['K1_graph']]
  
} else {
  print("Insufficient data for this question")
}


```

<!-- \ -->
<!-- \ -->
<!-- \ -->


<!-- ## **`r 'Q147'`** -->
<!-- ```{r K1a, fig.width = 10, fig.height = 5} -->

<!-- Count <- BaseCount %>% -->
<!--   filter(QuestionNumber == "K1a") %>%  -->
<!--   .$BaseSize -->


<!-- if  (Count > 5) { -->

<!--   Role         <- role_list$K1a_Roles -->
<!--   Role_caption <- paste(c(Role, Count, ' Responses'), collapse = " ") %>% str_wrap(50) -->

<!--   layout(matrix(c(1, 2), nrow = 2), heights = c(1, 4)) -->
<!--   par(mar = rep(0, 4)) -->
<!--   plot.new() -->
<!--   text(x = 0.5, y = 0.5, str_wrap(label_list[['K1a']], 40), cex = 2, font = 2) -->

<!--   SurveyWordCloud(Survey_data$K1a, c("candidates", "candidate")) -->

<!--   text(x = 0.5, y = 0, Role_caption, cex = 1.5, font = 3) -->

<!-- } else { -->
<!--   print("No data for this question") -->
<!-- } -->


<!-- ``` -->

\
\
\


## **`r 'Q148'`**
```{r K2, fig.width = 20, fig.height = 8}


if (is.null(plots_yesno[['K2_graph']]) == FALSE) {
  
  plots_yesno[['K2_graph']]
  
} else {
  print("Insufficient data for this question")
}

```

\
\
\

## **`r 'Q149'`**
```{r K4, fig.width = 24, fig.height = 8}

if (is.null(ord5_plots_sub[['K4_graph']]) == FALSE) {
  
  ord5_plots_sub[['K4_graph']]
  
} else {
  print("Insufficient data for this question")
}

```

<!-- \ -->
<!-- \ -->
<!-- \ -->

<!-- ## **`r 'Q150'`** -->
<!-- ```{r K4a, fig.width = 10, fig.height = 6} -->

<!-- Count <- BaseCount %>% -->
<!--   filter(QuestionNumber == "K4a") %>% -->
<!--   .$BaseSize -->


<!-- if  (Count > 5) { -->

<!--   Role         <- role_list$K4a_Roles -->
<!--   Role_caption <- paste(c(Role, Count, ' Responses'), collapse = " ") %>% str_wrap(50) -->

<!--   layout(matrix(c(1, 2), nrow = 2), heights = c(1, 4)) -->
<!--   par(mar = rep(0, 4)) -->
<!--   plot.new() -->
<!--   text(x = 0.5, y = 0.5, str_wrap(label_list[['K4a']], 40), cex = 2, font = 2) -->

<!--   SurveyWordCloud(Survey_data$K4a, c("candidates", "candidate")) -->

<!--   text(x = 0.5, y = 0, Role_caption, cex = 1.5, font = 3) -->

<!-- } else { -->
<!--   print("No data for this question") -->
<!-- } -->

<!-- ``` -->

\
\
\

## **`r 'IT Verbatims'`**

<!-- ```{r, echo=FALSE, message=FALSE, warning=FALSE} -->

<!-- datatable(IT_verbatims_LUT, -->

<!--           rownames   = FALSE, -->
<!--           extensions = 'Buttons', -->
<!--           filter     = 'top', -->
<!--           caption    = 'Counting Questions with Verbatim responses', -->

<!--           options      = list( -->
<!--             pageLength = 10 -->
<!--             ,dom       = 'tip') -->
<!--           ) %>% -->

<!--   formatStyle(columns = rep(1:length(IT_verbatims_LUT)), fontSize = "12pt") -->

<!-- ``` -->

<!-- \ -->

```{r, echo=FALSE, message=FALSE, warning=FALSE}

datatable(Survey_IT_verbatim_no %>% select(-'ReturningOffice: ', -'VenueName: '),

          rownames   = FALSE,
          extensions = 'Buttons',
          filter     = 'top',
          caption    = 'Verbatim responses to Voting Questions in the Local Election Staff Survey',

          options = list(
            pageLength = 10
            ,dom = 'tip'),

          height = '1200px') %>%

   formatStyle(columns = rep(1:length(Survey_IT_verbatim_no)), fontSize = "12pt")

```

