---
title: Survey questions
output: 
  html_document:
    theme: lumen           
    highlight: tango
---

<style type="text/css">

.main-container {
max-width: 1400px;
margin-left: 180px;
margin-right: auto;

}

</style>



## {.tabset .tabset-fade}

### All questions


<!-- Set alignment property for the following container -->
<div align="left">

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE, comment = NA}

datatable(table_of_contents
          
          # Set width of table in container, requires fillContainer to be set to FALSE
          ,width = '95%'
          ,fillContainer = FALSE
          
          ,rownames   = FALSE
          ,extensions = 'Buttons'
          ,filter     = 'top'
          ,caption    = 'Table of all questions asked'
          
          ,options = list(
            pageLength = 100
            ,dom = 'tip'
            ,scrollY = TRUE
            
            # Control individual column width (requires autoWidth to be set to TRUE)
            # targets argument refers to column postitions which are zero indexed
            ,autoWidth = TRUE
            ,columnDefs = list(list(width  = '150px', targets = c(0))
                               ,list(width = '50px', targets = c(1, 3))
            )))

```
</div>



### All 'satisfaction' responses



```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE, comment = NA}

datatable(Master_satisfaction_table_combined %>% 
            dplyr::select(-`Total`)
          
          ,width = '98%'
          ,fillContainer = FALSE
          
          ,rownames   = FALSE
          ,extensions = 'Buttons'
          ,filter     = 'top'
          ,caption    = 'Table of all responses to satisfaction questions'
          
          ,options = list(
            pageLength = 100
            ,dom = 'tip'
            ,scrollY = '100%'
            
            ,autoWidth = TRUE
            ,columnDefs = list(list(width = '150px', targets = c(0))
                               ,list(width = '50px', targets = c(1,4,5,6,7))
            )
          )
) %>% 
  
  ## Convert 
  formatPercentage(c('Satisfied', 'Neutral', 'Dissatisfied'), 1)


```





<!-- Index Calculation -->
<!-- ===================================== -->

<!-- Column {data-width = 1} -->
<!-- ----------------------------------------------------------------------- -->


<!-- Column {data-width = 12} -->
<!-- ----------------------------------------------------------------------- -->

<!-- \ -->

<!-- In the formatted staff survey data table, rows are people (n=1356), and the  -->
<!-- columns are questions (n = 382). The original data has been transformed, so   -->
<!-- every staff response (i.e. row) is assgined a numerical value between -1 and 1   -->
<!-- For example, for five-scale satisfaction questions, transformed values are   -->

<!-- \ -->
<!-- Very satisfactory    ~ 1, -->
<!-- \ -->
<!-- Satisfactory         ~ 0.5, -->
<!-- \ -->
<!-- Neutral              ~ 0, -->
<!-- \ -->
<!-- Unsatisfactory       ~ -0.5, -->
<!-- \ -->
<!-- Very unsatisfactory  ~ -1    -->
<!-- \ -->

<!-- For the questions in other formats (e.g. time hours worked), we use the  -->
<!-- distribution of values from all respondents for that question. For example  -->
<!-- for question 93 - time finished, the shortest time people worked was 10 hrs.  -->
<!-- The median hours worked was 15 hrs (i.e. starting around 8am, and finishing  -->
<!-- between 10-11pm), and the maximum was 16 hrs. So we assinged the first  -->
<!-- 'quarter' of the data range (10-14 hrs worked) a value of 1 (positive), the 'middle'  -->
<!-- of the data range (14-15 hrs) a value of 0 (i.e. neutral) and the last quarter    -->
<!-- of the data range (15-16 hrs worked) a values of -1 (negative), assuming working  -->
<!-- longer is a greater WHS risk. -->

<!-- \ -->

<!-- After 11pm     ~ -1,    -->
<!-- 10pm-11pm      ~ 0,        -->
<!-- 9pm-10pm       ~ 1,       -->
<!-- 8pm-9pm        ~ 1,       -->
<!-- 7pm-8pm        ~ 1,          -->
<!-- 6pm-7pm        ~ 1,          -->
<!-- During the day ~ 1    -->

<!-- \ -->

<!-- Using these numeric values, we then calculated the average numeric index for    -->
<!-- all questions within each theme. The index values were then aggregated to both    -->
<!-- the venue (n = 2175) and the district (n = 93). It is these aggregated indexes,    -->
<!-- ranging between -1 and +1, that we can compare to both the venue and district   -->
<!-- level workloads.     -->

<!-- \ -->

<!-- The indexes have been aggregated into a series of scatterplot matrices. These    -->
<!-- plot the indexes for each theme at the venue and district level in relation to    -->
<!-- each other, and also in relation to the voting workload. The variable    -->
<!-- 'District Workload' is the TotalVotes / Total_projections for each district    -->
<!-- (**Fig A**). Both variables are proxies for the stress each staff member would be under.    -->

<!-- \ -->

<!-- ```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE, comment = NA, fig.align = "center", fig.width=10, fig.height=5} -->

<!-- dist.votes.plot -->

<!-- ```      -->
<!-- **Fig A).** Histograms of the difference between projected and total votes at the district level.     -->
<!-- The remotess categories are taken from the ABS : https://www.abs.gov.au/websitedbs/d3310114.nsf/home/remoteness+structure.     -->

<!-- \ -->


<!-- Column {data-width = 1} -->
<!-- ----------------------------------------------------------------------- -->
