---
title: "Work, health & safety"
output:
  html_document:
    toc: true               # Table of content true
    toc_depth: 4            # Up to three depths of headings (specified by #, ## and html_document
    toc_float: true
    number_sections: false  # If you want number sections at each table header
  #   theme: united           # Many options for theme, this one is my favorite.
  #   highlight: tango        # Specifies the syntax highlighting style
  #   css: styles_demography.css
  # revealjs::revealjs_presentation:
  #   dev: 'svg'
  #   self_contained: false
  #   reveal_plugins: ["notes", "search"]
  #   reveal_options:
  #     slideNumber: true
  #     previewLinks: true
  # word_document:
  #   always_allow_html: yes
---


```{r setup, include = FALSE}

knitr::opts_chunk$set(echo          = FALSE, 
                      warning       = FALSE, 
                      message       = FALSE, 
                      warning       = FALSE, 
                      fig.fullwidth = TRUE, 
                      paged.print   = FALSE, 
                      comment       = NA)

```

\
\
\

## **`r 'Q2'`**
```{r A2, fig.width = 20, fig.height = 8}

plots_yesno[["A2_graph"]]

```

\
\
\

## **`r 'Q3'`**
```{r A2a, fig.width = 10, fig.height = 8}

Count <- BaseCount %>%
  filter(QuestionNumber == "A2a")  %>% 
  .$BaseSize 

if (Count >= 1) {
  
  Role         <- role_list$A2a_Roles
  Role_caption <- paste(c(Role, Count, ' Responses'), collapse = " ") %>% str_wrap(50)
  
  layout(matrix(c(1, 2), nrow = 2), heights = c(1, 4))
  par(mar = rep(0, 4))
  plot.new()
  text(x = 0.5, y = 0.5, str_wrap(label_list[['A2a']], 40), cex = 2, font = 2)
  
  SurveyWordCloud(Survey_data$A2a, c("covid", "candidate"))
  
  text(x = 0.5, y = 0, Role_caption, cex = 1.5, font = 3)
  
} else {
  print("No data for this question")
}


```

\
\
\

## **`r 'Q4'`**
```{r A3, fig.width = 20, fig.height = 8}

plots_yesno[['A3_graph']]

```

\
\
\

## **`r 'Q5'`**
```{r A3a, fig.width = 10, fig.height = 7}

Count <- BaseCount %>%
  filter(QuestionNumber == "A3a")  %>% 
  .$BaseSize 

if (Count >= 1) {
  
  Role         <- role_list$A3a_Roles
  Role_caption <- paste(c(Role, Count, ' Responses'), collapse = " ") %>% str_wrap(50)
  
  layout(matrix(c(1, 2), nrow = 2), heights = c(1, 4))
  par(mar = rep(0, 4))
  plot.new()
  text(x = 0.5, y = 0.5, str_wrap(label_list[['A3a']], 40), cex = 2, font = 2)
  
  SurveyWordCloud(Survey_data$A3a, c("candidates", "candidate"))
  
  text(x = 0.5, y = 0, Role_caption, cex = 2, font = 3)
  
  
} else {
  print("No data for this question")
}


```

\
\
\

## **`r 'Q6'`**
```{r A4, fig.width = 20, fig.height = 8}

plots_yesno[['A4_graph']]

```

\
\
\

## **`r 'Q7'`**
```{r A4a, fig.width = 10, fig.height = 8}

Count <- BaseCount %>%
  filter(QuestionNumber == "A4a")  %>% 
  .$BaseSize 

if (Count >= 1) {
  
  Role         <- role_list$A4a_Roles
  Role_caption <- paste(c(Role, Count, ' Responses'), collapse = " ") %>% str_wrap(50)
  
  layout(matrix(c(1, 2), nrow = 2), heights = c(1, 4))
  par(mar = rep(0, 4))
  plot.new()
  text(x = 0.5, y = 0.5, str_wrap(label_list[['A4a']], 40), cex = 2, font = 2)
  
  SurveyWordCloud(Survey_data$A4a, c("candidates", "candidate"))
  
  text(x = 0.5, y = 0, Role_caption, cex = 2, font = 3)
  
  
} else {
  print("No data for this question")
}


```

\
\
\


## **`r 'Q151'`**
```{r L1, fig.width = 20, fig.height = 8}

plots_yesno[['L1_graph']]

```

\
\
\

## **`r 'Q152'`**
```{r L1a, fig.width = 12, fig.height = 8}

plot_histograms[['L1a_graph']]

```

\
\
\

## **`r 'Q153'`**
```{r L1b, fig.width = 10, fig.height = 8}

Count <- BaseCount %>%
  filter(QuestionNumber == "L1b") %>% 
  .$BaseSize

if (Count > 3) {
  
  Role <- role_list$L1b_Roles
  
  layout(matrix(c(1, 2), nrow = 2), heights = c(1, 4))
  par(mar = rep(0, 4))
  plot.new()
  text(x = 0.5, y = 0.5, str_wrap(label_list[['L1b']], 40), cex = 1.8, font = 2)
  
  SurveyWordCloud(Survey_data$L1b, c("venue", "candidate"))
  
  text(x = 0.5, y = -0.028, Role_caption, cex = 1.2, font = 3)
  
} else {
  print("No data for this question")
}


```

\
\
\

## **`r 'Q154'`**
```{r L2, fig.width = 20, fig.height = 8}

if (is.null(plots_yesno[['L2_graph']]) == FALSE) {
  
  plots_yesno[["L2_graph"]]
  
} else {
  print("Insufficient data for this question")
}


```

\
\
\

## **`r 'Q155'`**
```{r L3, fig.width = 20, fig.height = 8}

if (is.null(plots_yesno[['L3_graph']]) == FALSE) {
  
  plots_yesno[["L3_graph"]]
  
} else {
  print("Insufficient data for this question")
}

```

\
\
\

## **`r 'Q156'`**
```{r L3a, fig.width = 12, fig.height = 8}

if (is.null(plot_histograms[['L3a_graph']]) == FALSE) {
  
  plot_histograms[['L3a_graph']]
  
} else {
  print("Insufficient data for this question")
}

```

\
\
\

## **`r 'Q157'`**
```{r L4, fig.width = 20, fig.height = 8}

if (is.null(plots_yesno[['L4_graph']]) == FALSE) {
  
  plots_yesno[['L4_graph']]
  
} else {
  print("Insufficient data for this question")
}

```

\
\
\

## **`r 'Q158'`**
```{r fig.width = 20, fig.height = 8}

if (is.null(plots_yesno[['L5_graph']]) == FALSE) {
  
  plots_yesno[['L5_graph']]
  
} else {
  print("Insufficient data for this question")
}

```

\
\
\

## **`r 'Q159'`**
```{r L6, fig.width = 20, fig.height = 8}

plots_yesno[['L6_graph']]

```

\
\
\

## **`r 'Q160'`**
```{r L6a, fig.width = 12, fig.height = 8}

plot_histograms[['L6a_graph']]

```

\
\
\

## **`r 'Q161'`**
```{r L7, fig.width = 20, fig.height = 8}

plots_yesno[['L7_graph']]

```

\
\
\

## **`r 'Q162'`**
```{r L7a, fig.width = 20, fig.height = 8}

plots_yesno[['L7a_graph']]

```

\
\
\

## **`r 'Q163'`**
```{r L7b, fig.width = 10, fig.height = 7}

Count <- BaseCount %>%
  filter(QuestionNumber == "L7b") %>% 
  .$BaseSize

if (Count >= 3) {
  
  Role <- role_list$L7b_Roles
  
  Role_caption <- paste(c(Role, Count, ' Responses'), collapse = " ") %>% str_wrap(50)
  
  layout(matrix(c(1, 2), nrow = 2), heights = c(1, 4))
  par(mar = rep(0, 4))
  plot.new()
  text(x = 0.5, y = 0.5, str_wrap(label_list[['L7b']], 40), cex = 2, font = 2)
  
  SurveyWordCloud(Survey_data$L7b, c("break", "breaks", "planner"))
  
  text(x = 0.5, y = 0, Role_caption, cex = 1.5, font = 3)
  
} else {
  print("No data for this question")
}

```

\
\
\

## **`r 'Q164'`**
```{r L8, fig.width = 15, fig.height = 8, fig.align='center'}

time_histograms[['L8_graph']]

```

\
\
\


## **`r 'Q165'`**
```{r L9, fig.width = 12, fig.height = 8}

plot_histograms[['L9_graph']]

```

\
\
\


## **`r 'Q166'`**
```{r L9a, fig.width = 15, fig.height = 8}

## These shouldn't be word clouds....
time_histograms[['L9a_graph']]

```

\
\
\


## **`r 'Q167'`**
```{r L9b, fig.width = 15, fig.height = 8}

time_histograms[['L9b_graph']]

```

\
\
\


## **`r 'Q168'`**
```{r L10, fig.width = 15, fig.height = 8, fig.align = 'center'}

## These shouldn't be word clouds....
time_histograms[['L10_graph']]

```

\
\
\



## **`r 'Q169'`**
```{r L11, fig.width = 20, fig.height = 8}

plots_yesno[['L11_graph']]

```

\
\
\


## **`r 'Q169'`**
```{r L11a, fig.width = 10, fig.height = 8, warning = FALSE}

Count <- BaseCount %>%
  filter(QuestionNumber == "L11a") %>% 
  .$BaseSize

if (Count >= 3) {
  
  Role         <- role_list$L11a_Roles
  Role_caption <- paste(c(Role, Count, ' Responses'), collapse = " ") %>% str_wrap(50)
  
  layout(matrix(c(1, 2), nrow = 2), heights = c(1, 4))
  par(mar = rep(0, 4))
  plot.new()
  text(x = 0.5, y = 0.5, str_wrap(label_list[['L11a']], 40), cex = 2, font = 2)
  
  ## These shouldn't be word clouds....
  SurveyWordCloud(Survey_data$L11a, c("candidates", "candidate"))
  
  text(x = 0.5, y = 0, Role_caption, cex = 1.3, font = 3)
  
  
} else {
  print("No data for this question")
}

```

\
\
\

## **`r 'WHS Verbatims'`**

<!-- ```{r, echo=FALSE, message=FALSE, warning=FALSE} -->

<!-- datatable(WHS_verbatims_LUT, -->

<!--           rownames   = FALSE, -->
<!--           extensions = 'Buttons', -->
<!--           filter     = 'top', -->
<!--           caption    = 'WHS Questions with Verbatim responses', -->

<!--           options      = list( -->
<!--             pageLength = 10 -->
<!--             ,dom       = 'tip')) %>% -->

<!--   formatStyle(columns = rep(1:length(WHS_verbatims_LUT)), fontSize = "12pt") -->

<!-- ``` -->

<!-- \ -->

```{r, echo=FALSE, message=FALSE, warning=FALSE}

datatable(Survey_WHS_verbatim_no %>% select(-'ReturningOffice: ', -'VenueName: '),
          
          rownames   = FALSE,
          extensions = 'Buttons',
          filter     = 'top',
          caption    = 'Verbatim responses to WHS Questions in the Local Election Staff Survey',
          
          options      = list(
            pageLength = 10,
            dom        = 'Btip',
            buttons    = c( 'csv', 'excel')),
          
          height = '1200px') %>%
  
  formatStyle(columns = rep(1:length(Survey_WHS_verbatim)), fontSize = "12pt")

```
